"""
Django settings for nusacrop_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from corsheaders.defaults import default_headers
import dj_database_url

from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',        
    'recommendation', 
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3004",
    "https://gemastik-softdev-burhan.vercel.app",
    "https://nusa-crop-gemastik.vercel.app",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

ROOT_URLCONF = 'nusacrop_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nusacrop_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"postgresql://postgres:{os.getenv('DB_PASSWORD')}@localhost:5432/nusacrop"
    )
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'nusacrop',
    #     'USER': 'postgres',
    #     'PASSWORD': os.getenv('DB_PASSWORD'),
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
}


# SQLite hanya untuk pengembangan lokal. Job & pengambilan data berjalan di
# beberapa thread, jadi pakai mode IMMEDIATE + timeout agar tidak "database is
# locked". Produksi (Railway) tetap PostgreSQL.
if DATABASES['default'].get('ENGINE', '').endswith('sqlite3'):
    DATABASES['default'].setdefault('OPTIONS', {}).update(
        {'transaction_mode': 'IMMEDIATE', 'timeout': 20, 'init_command': 'PRAGMA journal_mode=WAL;'})


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'id'  # pesan validasi DRF/Django dalam bahasa Indonesia

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------- NUSA-CROP
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "recommendation.utils.respons.exception_handler",
    "DEFAULT_THROTTLE_CLASSES": ["rest_framework.throttling.AnonRateThrottle"],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("THROTTLE_ANON", "120/min"),         # termasuk polling status job
        "analisis": os.getenv("THROTTLE_ANALISIS", "10/min"),  # analisis lahan (mahal)
        # satu HP dipakai bergantian beberapa peserta usability test
        "usability": os.getenv("THROTTLE_USABILITY", "600/min"),
    },
}

# ---------------------------------------------------------------- domain .id
# Contoh di Railway:
#   DJANGO_ALLOWED_HOSTS=api.nusacrop.id,<domain-railway-lama>
#   CORS_EXTRA_ORIGINS=https://nusacrop.id,https://www.nusacrop.id
#   CSRF_TRUSTED_ORIGINS=https://api.nusacrop.id
#   NUSACROP_SITE_URL=https://nusacrop.id
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]
# Railway meneruskan HTTPS lewat proxy; tanpa ini Django mengira request-nya
# HTTP, sehingga login /admin/ di domain kustom gagal karena cek CSRF.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
NUSACROP_SITE_URL = os.getenv("NUSACROP_SITE_URL", "https://nusa-crop-gemastik.vercel.app")

# domain FE tambahan tanpa ubah kode, pisahkan dengan koma
CORS_ALLOWED_ORIGINS += [o.strip() for o in os.getenv("CORS_EXTRA_ORIGINS", "").split(",") if o.strip()]
# preview deploy Vercel (mis. nusa-crop-git-feature-xxx.vercel.app); kosongkan untuk menonaktifkan
CORS_ALLOWED_ORIGIN_REGEXES = [r for r in os.getenv(
    "CORS_ORIGIN_REGEX", r"^https://nusa-crop[a-z0-9-]*\.vercel\.app$").split(",") if r]

# Antrian job: isi REDIS_URL (Railway Redis) untuk memakai Celery.
# Kosong = thread pool di dalam proses web (cukup untuk demo).
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL") or os.getenv("REDIS_URL") or None
CELERY_RESULT_BACKEND = None
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# harga kapur (Rp/kg) untuk perkiraan biaya simulasi pengapuran; kosong = tidak dihitung
HARGA_KAPUR_PER_KG = int(os.getenv("HARGA_KAPUR_PER_KG")) if os.getenv("HARGA_KAPUR_PER_KG") else None

# True = simulasi kapur memakai angka CONTOH selama ml_lib/pengapuran.py belum ada
# (untuk pengembangan FE). Modul asli tim ML selalu diutamakan bila tersedia.
NUSACROP_PENGAPURAN_CONTOH = os.getenv("NUSACROP_PENGAPURAN_CONTOH", "False") == "True"

NUSACROP_PARALEL = True        # ambil tanah/iklim/satelit secara paralel
NUSACROP_JOB_SINKRON = False   # True di tes: job dijalankan langsung

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {"recommendation": {"handlers": ["console"], "level": "INFO"}},
}
