# Generated by Django 6.0.7 on 2026-08-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('nama_latin', models.CharField(max_length=150)),
                ('deskripsi', models.TextField()),
                ('jenis_tanaman', models.CharField(max_length=100)),
                ('umur_panen', models.CharField(max_length=100)),
                ('potensi_hasil', models.CharField(max_length=100)),
                ('manfaat', models.TextField()),
                ('cara_budidaya', models.TextField()),
                ('syarat_tumbuh', models.JSONField()),
            ],
        ),
    ]
