# Generated by Django 6.0.7 on 2026-08-09 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPencarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(db_index=True, max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('luas_lahan', models.FloatField(blank=True, null=True)),
                ('musim_target', models.CharField(blank=True, max_length=50, null=True)),
                ('curah_hujan', models.FloatField(blank=True, null=True)),
                ('ph_tanah', models.FloatField(blank=True, null=True)),
                ('elevasi', models.FloatField(blank=True, null=True)),
                ('suhu', models.FloatField(blank=True, null=True)),
                ('et0', models.FloatField(blank=True, null=True)),
                ('nitrogen', models.FloatField(blank=True, null=True)),
                ('organic_carbon', models.FloatField(blank=True, null=True)),
                ('tekstur_tanah', models.JSONField(default=dict)),
                ('kesuburan_tanah', models.FloatField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatRekomendasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor_kesesuaian', models.FloatField()),
                ('ranking', models.PositiveSmallIntegerField()),
                ('tingkat_kepercayaan', models.CharField(default='Sedang', max_length=50)),
                ('alasan_rekomendasi', models.JSONField(default=list)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommendation.crop')),
                ('riwayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekomendasi', to='recommendation.riwayatpencarian')),
            ],
            options={
                'ordering': ['ranking'],
                'constraints': [models.UniqueConstraint(fields=('riwayat', 'crop'), name='unique_crop_history')],
            },
        ),
    ]
