# Generated by Django 6.0.7 on 2026-08-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_riwayatpencarian_riwayatrekomendasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatpencarian',
            name='ndvi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
