# Generated by Django 6.0.7 on 2026-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_riwayatpencarian_ndvi'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatpencarian',
            name='nama_lokasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
