# Generated by Django 6.0.7 on 2026-08-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_riwayatpencarian_nama_lokasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='potensi_hasil',
            new_name='produktivitas_tanaman',
        ),
        migrations.RemoveField(
            model_name='riwayatpencarian',
            name='luas_lahan',
        ),
    ]
