# Generated by Django 6.0.7 on 2026-08-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_rename_potensi_hasil_crop_produktivitas_tanaman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatrekomendasi',
            name='jenis_tanaman',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
