# Generated by Django 6.0.7 on 2026-08-16 07:28

from django.db import migrations

def backfill_jenis_tanaman(apps, schema_editor):
    RiwayatRekomendasi = apps.get_model('recommendation', 'RiwayatRekomendasi')
    for rek in RiwayatRekomendasi.objects.filter(jenis_tanaman__isnull=True).select_related('crop'):
        rek.jenis_tanaman = rek.crop.jenis_tanaman
        rek.save(update_fields=['jenis_tanaman'])
        
def reverse_backfill(apps, schema_editor):
    #buat jg2 kalo rollback
    RiwayatRekomendasi = apps.get_model('recommendation', 'RiwayatRekomendasi')
    RiwayatRekomendasi.objects.update(jenis_tanaman=None)
    
            
class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_riwayatrekomendasi_jenis_tanaman'),
    ]

    operations = [
        migrations.RunPython(backfill_jenis_tanaman, reverse_backfill),
    ]
