# Generated by Django 6.0.7 on 2026-10-03 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_backfill_jenis_tanaman'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(db_index=True, max_length=100)),
                ('input', models.JSONField()),
                ('status', models.CharField(choices=[('antri', 'Antri'), ('berjalan', 'Berjalan'), ('selesai', 'Selesai'), ('perlu_input', 'Perlu input tambahan'), ('gagal', 'Gagal')], default='antri', max_length=20)),
                ('progres', models.JSONField(default=dict)),
                ('hasil', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='UsabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(db_index=True, max_length=100)),
                ('sesi_id', models.CharField(db_index=True, max_length=100)),
                ('event', models.CharField(max_length=50)),
                ('tugas', models.CharField(blank=True, max_length=50, null=True)),
                ('berhasil', models.BooleanField(blank=True, null=True)),
                ('durasi_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('waktu_klien', models.DateTimeField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['dibuat_pada'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='biaya_produksi_per_ha',
            field=models.PositiveBigIntegerField(blank=True, help_text='Rupiah per hektar per musim tanam', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='produktivitas_max_ton_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='produktivitas_min_ton_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='sumber_biaya',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='tahun_biaya',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatpencarian',
            name='bulan_tanam',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatpencarian',
            name='kemiringan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatpencarian',
            name='kualitas_data',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatpencarian',
            name='sumber_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='riwayatpencarian',
            name='uji_tanah',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatrekomendasi',
            name='faktor_pembatas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='riwayatrekomendasi',
            name='mulai_tanam',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='riwayatrekomendasi',
            name='musim_tanam_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatrekomendasi',
            name='rincian_skor',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='DataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber', models.CharField(max_length=20)),
                ('kunci_sel', models.CharField(max_length=40)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('payload', models.JSONField()),
                ('diambil_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sumber', 'lat', 'lon'], name='recommendat_sumber_c0650b_idx')],
                'constraints': [models.UniqueConstraint(fields=('sumber', 'kunci_sel'), name='unique_cache_sel')],
            },
        ),
        migrations.CreateModel(
            name='LahanTanam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(db_index=True, max_length=100)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=50)),
                ('tanggal_tanam', models.DateField()),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('panen', 'Sudah panen'), ('gagal', 'Gagal'), ('dihentikan', 'Dihentikan')], default='aktif', max_length=20)),
                ('kesehatan', models.CharField(default='belum_cukup_data', max_length=30)),
                ('peringatan', models.JSONField(default=list)),
                ('terakhir_dipantau', models.DateTimeField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommendation.crop')),
                ('rekomendasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lahan_tanam', to='recommendation.riwayatrekomendasi')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackPengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(db_index=True, max_length=100)),
                ('jenis', models.CharField(choices=[('rekomendasi', 'Tanggapan atas rekomendasi'), ('hasil_panen', 'Hasil panen'), ('aplikasi', 'Masukan aplikasi')], max_length=20)),
                ('ditanam', models.BooleanField(blank=True, null=True)),
                ('hasil', models.CharField(blank=True, choices=[('baik', 'Baik'), ('sedang', 'Sedang'), ('buruk', 'Buruk'), ('gagal', 'Gagal')], max_length=10, null=True)),
                ('hasil_panen_kg', models.FloatField(blank=True, null=True)),
                ('luas_lahan_m2', models.FloatField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('komentar', models.TextField(blank=True, default='')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('rekomendasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.riwayatrekomendasi')),
                ('lahan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.lahantanam')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='HargaKomoditas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('tingkat', models.CharField(choices=[('produsen', 'Produsen'), ('konsumen', 'Konsumen')], default='produsen', max_length=10)),
                ('harga_per_kg', models.PositiveIntegerField(help_text='Rupiah per kg')),
                ('wilayah_kode', models.CharField(blank=True, max_length=20, null=True)),
                ('wilayah_nama', models.CharField(blank=True, max_length=100, null=True)),
                ('sumber', models.CharField(blank=True, max_length=100, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harga', to='recommendation.crop')),
            ],
            options={
                'ordering': ['-tanggal'],
                'indexes': [models.Index(fields=['crop', 'tingkat', '-tanggal'], name='recommendat_crop_id_213c5f_idx')],
                'constraints': [models.UniqueConstraint(fields=('crop', 'tanggal', 'tingkat', 'wilayah_kode'), name='unique_harga_per_hari')],
            },
        ),
        migrations.CreateModel(
            name='ObservasiNdvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('ndvi', models.FloatField()),
                ('piksel_valid', models.PositiveIntegerField(blank=True, null=True)),
                ('lahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observasi', to='recommendation.lahantanam')),
            ],
            options={
                'ordering': ['tanggal'],
                'constraints': [models.UniqueConstraint(fields=('lahan', 'tanggal'), name='unique_observasi_harian')],
            },
        ),
    ]
