# Generated by Django 6.0.7 on 2026-10-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_fitur_ekonomi_cache_job_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='lahantanam',
            name='luas_lahan_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatpencarian',
            name='curah_hujan_bulanan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatpencarian',
            name='luas_lahan_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatpencarian',
            name='tekstur_kelas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
