# Generated by Django 6.0.7 on 2026-10-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0009_luas_lahan_dan_simulasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatpencarian',
            name='hasil_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatrekomendasi',
            name='daftar',
            field=models.CharField(default='utama', max_length=20),
        ),
        migrations.AddField(
            model_name='riwayatrekomendasi',
            name='detail_kepercayaan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usabilityevent',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usabilityevent',
            name='halaman',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usabilityevent',
            name='mode_tes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usabilityevent',
            name='peserta',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usabilityevent',
            name='anonymous_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usabilityevent',
            name='event',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
